### ISSUE TITLE
ENOTCONN when trying simple .js example

### ISSUE THREAD

**Issue by nascif** [codegl/tracegl#103]
Running on Windows 7, inside a cygwin bash shell, with latest node.js (0.10.17)
File runs just fine under node. It implements a simple http server. Just trying to see how it works. But I got this:

$ node ./tracegl.js examples/hello.js
[trace.GL] See your code. This product has a commercial license.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ENOTCONN
    at errnoException (net.js:901:11)
    at Socket._read (net.js:391:21)
    at Socket.Readable.read (_stream_readable.js:320:10)
    at Socket.read (net.js:293:43)
    at new Socket (net.js:185:10)
    at process.stdin (node.js:660:19)
    at nodeJSMode (C:\dropbox\src\trace.gl\tracegl.js:577:24)
    at processArgs (C:\dropbox\src\trace.gl\tracegl.js:278:44)
    at Object./trace/trace_server (C:\dropbox\src\trace.gl\tracegl.js:288:9)
    at Object.<anonymous> (C:\dropbox\src\trace.gl\tracegl.js:13612:38)

Other modes not working either.

**Comment by nascif** [comment]
Doing a little research I found that this issue is common when running node.js inside a cygwin shell. I am using the windows command shell now and I got better results - although not complete success yet. I never got the 0.0.0.0:2000 access to work but it does work if I use 127.0.0.1:2000. Well, it doesn't fail with an HTTP error, and I do see the window title changing to traceGL - but all I see is a black screen. I tested and my browser (Chrome) does support webGL...
