### ISSUE TITLE
Message order error 153649 1

### ISSUE THREAD

**Issue by intuitivepixel** [codegl/tracegl#67]
I'm trying to visualize a rather large project including jquery, ember.js, handlebars.js and some more js files, this files get concatenated into on big js file and thats referenced in my index.html file inside the target path I'm giving as a parameter, but I get this error and the node process exits:

> node tracegl.js ../projects/app/dist/
> [trace.GL] See your code. This product has a commercial license.
> [trace.GL] WebGL trace UI: http://localhost:2000
> [trace.GL] Checking for update...[trace.GL] Serving browser JS: http://localhost:2080
> up to date.
> Message order error 153659 1
> 
> events.js:71
>         throw arguments[1]; // Unhandled 'error' event
>                        ^
> Error: socket hang up
>     at createHangUpError (http.js:1360:15)
>     at ServerResponse.OutgoingMessage._writeRaw (http.js:507:26)
>     at ServerResponse.OutgoingMessage._send (http.js:476:15)
>     at ServerResponse.OutgoingMessage.end (http.js:890:18)
>     at endPoll (/Users/alex/Desktop/tracegl.js:3549:8)
>     at Timer.<anonymous> (/Users/alex/Desktop/tracegl.js:3558:34)
>     at Timer.exports.setInterval.timer.ontimeout (timers.js:234:14)

I'm on a Mac OSX 10.8.3
node version v0.8.20

Any idea why this happens?

**Comment by tanepiper** [comment]
[Duplicate of issue 28](https://github.com/codegl/tracegl/issues/28)
