### ISSUE TITLE
Mocha breaks while tracing

### ISSUE THREAD

**Issue by 3rd-Eden** [codegl/tracegl#84]
Not sure what the cause of this is but when I attempt to trace small section of a test suite that has a race condition, it throws an exception. I'm assuming the fault lies within tracegl as running without tracegl results in a working test suite:

```
NODE_ENV=testing node ~/tracegl ./node_modules/.bin/_mocha test/client.test.js                             ~/Projects/observing/[redacted] 1 ↵
[trace.GL] See your code. This product has a commercial license.
[trace.GL] WebGL trace UI: http://0.0.0.0:2000
[trace.GL] Checking for update...
/Users/V1/Projects/observing/[redacted]/node_modules/mocha/bin/_mocha:1
on(i, a, t, u){if(lr) _$_.ch.send(lr, 1), lr = 0;dp ++;if(!di) di = setTimeout
                                                                    ^
TypeError: undefined is not a function
    at Object._$_.f (/Users/V1/Projects/observing/[redacted]/node_modules/mocha/bin/_mocha:1:3940)
    at Object.<anonymous> (/Users/V1/Projects/observing/[redacted]/node_modules/mocha/bin/_mocha:7:15)
    at Module._compile (module.js:449:26)
    at Module.m._compile (/Users/V1/Dropbox/tracegl.js:42:22)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at Function.require (module.js:378:17)
    at nodeLoader (/Users/V1/Dropbox/tracegl.js:48:10)
up to date.
```

Running it as plain node app works as intended:

```
NODE_ENV=testing node ./node_modules/.bin/_mocha test/client.test.js
```

If you are wondering why i'm not using the `mocha` file directly it's because it spins up a child_process with `_mocha` which makes it impossible to trace what happens in the test suite as `child_processes` aren't traced.

**Comment by codegl** [comment]
Hi, so this is weird, under mocha both Date and setTimeout are undefined.
Edit tracegl line 3998 and change
                    if(!di) di = setTimeout(function(){di = dp = 0},0)
                    var r = {i:i, g:gc++, d:dp, u:u, t:Date.now()}
to
                    if(!di) di = global.setTimeout(function(){di = dp = 0},0)
                    var r = {i:i, g:gc++, d:dp, u:u, t:global.Date.now()}
and you now have a trace.
I'm not sure if this is a general fix i can push though, but it'l fix your issue (it did here atleast)

**Comment by 3rd-Eden** [comment]
It fixes the issue partially. It doesn't crash anymore but it just stops when it reaches the first test. When I look at the UI the only thing i see is a spam of `proto.emit(drain)` as seen in this screenshot: http://cl.ly/image/0l0Z0o010l2N

**Comment by codegl** [comment]
It works in my test, i can't recreate your issue unfortunately

**Comment by 3rd-Eden** [comment]
I can e-mail you a snapshot of the code if you want.

**Comment by 3rd-Eden** [comment]
It's just dying out of memory because of it:

```
[trace.GL] See your code. This product has a commercial license.
[trace.GL] WebGL trace UI: http://0.0.0.0:2000
[trace.GL] Checking for update...up to date.


  Client
FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory
```

**Comment by 3rd-Eden** [comment]
In addition to that, it also causes the UI go out of memory: http://cl.ly/image/2K3z1y1q1N3j

**Comment by codegl** [comment]
Well it is possible to generate 'too much codeflow' for the tracer to run both on the node.js as on the UI side. I'll have to look at blocking the process whilst the buffer streams to the UI, and keep (semi) compressed buffers in the UI backing the data instead of spawning JS structures from it. This is a rather large rewrite, but i'm considering it.

**Comment by 3rd-Eden** [comment]
Yes, tracing large and active project would probably generate to much codeflow, but in this it might be solved by grouping / folding the code flow as they are all the same lines of code, it doesn't really add much value to see the same line of code a million times unless there's an actual value change happening inside of the code.
