### ISSUE TITLE
CERT_HAS_EXPIRED

### ISSUE THREAD

**Issue by rhysbrettbowen** [codegl/tracegl#90]
running it thorugh localhost but it has an expired certificate - can just click proceed on chrome to continue testing but throws an error:

C:\Users\Rhys\Downloads>node tracegl.js https://localhost:28443
[trace.GL] See your code. This product has a commercial license.
[trace.GL] WebGL trace UI: http://0.0.0.0:2000
[trace.GL] Checking for update...[trace.GL] Proxying browser JS: http://0.0.0.0:
2080 -> https://localhost:28443
up to date.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: CERT_HAS_EXPIRED
    at SecurePair.<anonymous> (tls.js:1283:32)
    at SecurePair.EventEmitter.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:896:10)
    at CleartextStream.read [as _read](tls.js:430:15)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at EncryptedStream.write [as _write](tls.js:344:25)
    at doWrite (_stream_writable.js:219:10)
    at writeOrBuffer (_stream_writable.js:209:5)
    at EncryptedStream.Writable.write (_stream_writable.js:180:11)
    at write (_stream_readable.js:573:24)

how can I get around this?

**Comment by rhysbrettbowen** [comment]
solved by adding:

rejectUnauthorized: false,
                requestCert: true,
                agent: false

to line 4674 (options for the request)
